()

diff --git a/bin/piad b/bin/piad
--- a/bin/piad
+++ b/bin/piad
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. &> /dev/null || \
-    echo "Failed to change directory to the script directory." && exit 1
+    ( echo "Failed to change directory to the script directory." && exit 1 )
 
 source lib/util.sh
 
